feat: Add UnixFS-based FsNode with encoding/decoding
0glabs/0g-storage-client pull request #43
Opened 2024-08-16 09:28 UTC by wanliqun

- Implemented the FsNode data structure to represent file and directory hierarchies using UnixFS.
- Added support for encoding FsNode into UnixFS format and decoding back into the FsNode structure.
- Included unit tests to verify the correctness of serialization and deserialization processes etc.

2024-08-19 08:08 UTC, boqiu requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: all files reviewed, 8 unresolved discussions (waiting on @wanliqun)

___
*[`transfer/unixfs/fs.go` line 30 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dYbKO9hWXIfDs09mM:-O4dYbKO9hWXIfDs09mN:b1kc4tm) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L30)):*
> ```Go
> 	Name    string    `json:"name"`              // File or directory name
> 	Type    FileType  `json:"type"`              // Type of the node (file or directory)
> 	Size    int64     `json:"size,omitempty"`    // File size in bytes (omitted for directories)
> ```

`only for files` as below
___
*[`transfer/unixfs/fs.go` line 31 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dYsxIBWhbegpIEfWw:-O4dYsxL6xvr-e6KocYx:b-7kxl5z) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L31)):*
> ```Go
> 	Type    FileType  `json:"type"`              // Type of the node (file or directory)
> 	Size    int64     `json:"size,omitempty"`    // File size in bytes (omitted for directories)
> 	Hash    string    `json:"hash,omitempty"`    // Merkle root hash (only for files)
> ```

Why directory do not have root hash?
___
*[`transfer/unixfs/fs.go` line 52 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4d_G0f-D7GOQGCTSN4:-O4d_G0f-D7GOQGCTSN5:b378vdn) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L52)):*
> ```Go
> 	// Insert and sort the new file at the correct position
> 	node.Entries = append(node.Entries, file)
> 	node.sort()
> ```

use btree instead?
___
*[`transfer/unixfs/fs.go` line 58 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4d_ica317CV7PP9i_I:-O4d_ica317CV7PP9i_J:b-7oec14) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L58)):*
> ```Go
> 
> // BatchAdd adds multiple files or directories to the current directory and sorts once.
> func (node *FsNode) BatchAdd(entries []*FsNode) error {
> ```

Why not merge with `Add` method, e.g. `Add(entries ...*FsNode)`?
___
*[`transfer/unixfs/fs.go` line 64 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4d_uizC99NqDujHe3d:-O4d_uizC99NqDujHe3e:b-2g41p9) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L64)):*
> ```Go
> 
> 	// Append all new entries
> 	node.Entries = append(node.Entries, entries...)
> ```

What if file already exists?
___
*[`transfer/unixfs/fs.go` line 72 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4da4qZ1PsunRtOFGCx:-O4da4qZ1PsunRtOFGCy:b-ffp3zc) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L72)):*
> ```Go
> 
> // Update updates an existing file's metadata within the directory.
> func (node *FsNode) Update(file *FsNode) error {
> ```

Could merge with `Add` method? Maybe `insert` is a better name.
___
*[`transfer/unixfs/fs.go` line 88 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dfKRS9Sgb2phoPNud:-O4dfKRS9Sgb2phoPNue:basobsy) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L88)):*
> ```Go
> 
> // Rename renames a file or directory within the directory and keeps the entries sorted.
> func (node *FsNode) Rename(oldName, newName string) error {
> ```

please consider to provide `diff` cli for different versions of folders.
___
*[`transfer/unixfs/util.go` line 10 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dY22w1BU16n296RBo:-O4dY22w1BU16n296RBp:b-bj9f25) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/util.go#L10)):*
> ```Go
> // GetMerkleTreeRootOfFile calculates and returns the Merkle tree root hash of a given file.
> // It opens the file, generates the Merkle tree, and returns the root hash as a hexadecimal string.
> func GetMerkleTreeRootOfFile(filename string) (string, error) {
> ```

How about moving this utility to relevant package?


<!-- Sent from Reviewable.io -->

2024-08-20 07:40 UTC, wanliqun reviewed
Fixed

> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-:-O4iieNVBXRUGQZP0fD7:b-886gsx)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @boqiu)

___
*[`transfer/unixfs/fs.go` line 30 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dYbKO9hWXIfDs09mM:-O4iiVa-2I75TFLXUDjv:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L30)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`only for files` as below
</blockquote></details>

Done.
___
*[`transfer/unixfs/fs.go` line 31 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dYsxIBWhbegpIEfWw:-O4iiWs28oaICk4-NpuU:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L31)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why directory do not have root hash?
</blockquote></details>

Done.
___
*[`transfer/unixfs/fs.go` line 52 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4d_G0f-D7GOQGCTSN4:-O4iiXN65jG-PnzLAzF2:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L52)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

use btree instead?
</blockquote></details>

Done.
___
*[`transfer/unixfs/fs.go` line 58 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4d_ica317CV7PP9i_I:-O4iiXz4EzdfEw2TKbdy:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L58)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not merge with `Add` method, e.g. `Add(entries ...*FsNode)`?
</blockquote></details>

Done.
___
*[`transfer/unixfs/fs.go` line 64 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4d_uizC99NqDujHe3d:-O4iiYbsAQ3SPIPsDlAP:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L64)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

What if file already exists?
</blockquote></details>

Done.
___
*[`transfer/unixfs/fs.go` line 72 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4da4qZ1PsunRtOFGCx:-O4iiZ7U8-n8wsvHPJN5:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L72)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Could merge with `Add` method? Maybe `insert` is a better name.
</blockquote></details>

Done.
___
*[`transfer/unixfs/fs.go` line 88 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dfKRS9Sgb2phoPNud:-O4iiZk9CxLdUpGHgYm4:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/fs.go#L88)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

please consider to provide `diff` cli for different versions of folders.
</blockquote></details>

Done.
___
*[`transfer/unixfs/util.go` line 10 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O4dY22w1BU16n296RBo:-O4iiaETA4GS3zB810LN:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/dfd45f3397ce428afd2073514cbd0ac6f9832a95/transfer/unixfs/util.go#L10)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about moving this utility to relevant package?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-30 09:11 UTC, boqiu requested changes
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: all files reviewed, 11 unresolved discussions (waiting on @wanliqun)

___
*[`transfer/dir/codec.go` line 19 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XOB1mDyXdYYNSvefv:-O5XOB1mDyXdYYNSvefw:bm2u49n) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/codec.go#L19)):*
> ```Go
> 
> // EncodeFsNode serializes an FsNode into a custom binary format with magic bytes and versioning.
> func EncodeFsNode(node *FsNode) ([]byte, error) {
> ```

How about to implement the standard `encoding.BinaryMarshaler` interface for `FsNode`?
___
*[`transfer/dir/codec.go` line 48 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XPMmI3JWO4KrdLXgC:-O5XPMmI3JWO4KrdLXgD:b-w2m7m4) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/codec.go#L48)):*
> ```Go
> 
> // DecodeFsNode deserializes an FsNode from a custom binary format with magic bytes and versioning.
> func DecodeFsNode(data []byte) (*FsNode, error) {
> ```

How about to implement the standard `encoding.BinaryUnmarshaler` interface for `FsNode`?
___
*[`transfer/dir/codec.go` line 63 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XRRuWDyxwJKqpqeMN:-O5XRRuWDyxwJKqpqeMO:bc4rt4m) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/codec.go#L63)):*
> ```Go
> 	// Verify codec version
> 	var version uint16
> 	if err := binary.Read(buf, binary.BigEndian, &version); err != nil {
> ```

Is there any error if no enough data in `buf`?

Basically, it is very easy to check the length for magic number and version, and just use slice along with offset is enough to decode data.
___
*[`transfer/dir/diff.go` line 15 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XSC3J7My_Kh80l23J:-O5XSC3J7My_Kh80l23K:b-6ep3z) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/diff.go#L15)):*
> ```Go
> 	Removed   DiffStatus = "removed"
> 	Modified  DiffStatus = "modified"
> 	Unchanged DiffStatus = "unchanged"
> ```

Better to and `DiffStatus` as prefix for all above const variables.
___
*[`transfer/dir/fs.go` line 19 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XUc5e-EAcfSKjNgN-:-O5XUc5e-EAcfSKjNgN0:b-n3e2fl) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L19)):*
> ```Go
> 
> const (
> 	File      FileType = "file"
> ```

Better to add prefix `FileType`.
___
*[`transfer/dir/fs.go` line 21 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XUj1-BlW1tfHpFjO1:-O5XUj1-BlW1tfHpFjO2:b-yj6vnt) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L21)):*
> ```Go
> 	File      FileType = "file"
> 	Directory FileType = "directory"
> 	Symbolic  FileType = "symbolic"
> ```

How about `raw` data? E.g. small files (1-4 KB) could be wrapped in IPLD object.
___
*[`transfer/dir/fs.go` line 28 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XV8Co0PacVbJ0gLun:-O5XV8Cp02sWVnf7IBGW:b-l519ap) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L28)):*
> ```Go
> 	Name    string      `json:"name"`              // File or directory name
> 	Type    FileType    `json:"type"`              // File type of the node
> 	Hash    common.Hash `json:"hash,omitempty"`    // Merkle hash
> ```

Should be not empty all the time?



_Code quote:_
```Go
omitempty
```
___
*[`transfer/dir/fs.go` line 59 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XWEC26mJyxvI6lmHq:-O5XWEC26mJyxvI6lmHr:bz1is42) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L59)):*
> ```Go
> 
> 	root = crypto.Keccak256Hash(entries[len(entries)-1].Hash[:])
> 	for i := len(entries) - 2; i >= 0; i-- {
> ```

may overflow? e.g. only 1 entry.
___
*[`transfer/dir/fs.go` line 81 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XWcm14HS7GtS0jIAd:-O5XWcm14HS7GtS0jIAe:b-fhm3kt) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L81)):*
> ```Go
> 		Name: name,
> 		Type: Symbolic,
> 		Hash: crypto.Keccak256Hash([]byte(link)),
> ```

It seems `Hash` is useless for symbol link, right?
___
*[`transfer/dir/fs.go` line 89 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XXmtT6cD4mICxcICM:-O5XXmtT6cD4mICxcICN:b80a7cc) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L89)):*
> ```Go
> func (node *FsNode) Search(fileName string) (*FsNode, bool) {
> 	i, found := sort.Find(len(node.Entries), func(i int) int {
> 		return strings.Compare(fileName, node.Entries[i].Name)
> ```

Why not return `bool`? I think you want to find the `FsNode` with exact name, right?
___
*[`transfer/dir/fs.go` line 115 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XY2CJCR5hJB74KunX:-O5XY2CJCR5hJB74KunY:b-5upk5e) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L115)):*
> ```Go
> 
> 	// Root directory represented as "."
> 	root.Name = "."
> ```

Retrieve the `dir` name from path?


<!-- Sent from Reviewable.io -->

2024-09-02 08:52 UTC, wanliqun reviewed
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: 10 of 16 files reviewed, 11 unresolved discussions (waiting on @boqiu)

___
*[`transfer/dir/codec.go` line 19 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XOB1mDyXdYYNSvefv:-O5lfHklAAwSdhA3vcbh:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/codec.go#L19)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to implement the standard `encoding.BinaryMarshaler` interface for `FsNode`?
</blockquote></details>

Done.
___
*[`transfer/dir/codec.go` line 48 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XPMmI3JWO4KrdLXgC:-O5lfIvdDaiYqIw7bMU3:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/codec.go#L48)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to implement the standard `encoding.BinaryUnmarshaler` interface for `FsNode`?
</blockquote></details>

Done.
___
*[`transfer/dir/codec.go` line 63 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XRRuWDyxwJKqpqeMN:-O5lfMR61TpefnbQDcEh:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/codec.go#L63)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is there any error if no enough data in `buf`?

Basically, it is very easy to check the length for magic number and version, and just use slice along with offset is enough to decode data.
</blockquote></details>

Done.
___
*[`transfer/dir/diff.go` line 15 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XSC3J7My_Kh80l23J:-O5lfNt73w6CerIxV94S:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/diff.go#L15)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to and `DiffStatus` as prefix for all above const variables.
</blockquote></details>

Done.
___
*[`transfer/dir/fs.go` line 19 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XUc5e-EAcfSKjNgN-:-O5lfOkE3ldwjjjYe0Ph:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L19)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to add prefix `FileType`.
</blockquote></details>

Done.
___
*[`transfer/dir/fs.go` line 21 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XUj1-BlW1tfHpFjO1:-O5lfPbr5zydylfkU-MV:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L21)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about `raw` data? E.g. small files (1-4 KB) could be wrapped in IPLD object.
</blockquote></details>

Done.
___
*[`transfer/dir/fs.go` line 28 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XV8Co0PacVbJ0gLun:-O5lfdAdCI9ZnDHM3wQX:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Should be not empty all the time?
</blockquote></details>

Done.
___
*[`transfer/dir/fs.go` line 59 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XWEC26mJyxvI6lmHq:-O5lgmnkDlhQ0Ws4Kp0H:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L59)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

may overflow? e.g. only 1 entry.
</blockquote></details>

Done.
___
*[`transfer/dir/fs.go` line 81 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XWcm14HS7GtS0jIAd:-O5lh-dr9Avmx9x6hAmq:b-h06z8q) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L81)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

It seems `Hash` is useless for symbol link, right?
</blockquote></details>

It can be used for diff two symbolic links just like other types like directory or raw file etc.
___
*[`transfer/dir/fs.go` line 89 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XXmtT6cD4mICxcICM:-O5li2ehDZY3DJ8mUAsk:b-601zmg) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L89)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not return `bool`? I think you want to find the `FsNode` with exact name, right?
</blockquote></details>

I guess you mean by using `sort.Search` instead, if so that would be rather verbose to achieve the same result:
`
// Ensure that entries are sorted by name
idx := sort.Search(len(node.Entries), func(i int) bool {
  return node.Entries[i].Name >= fileName
})

// Check if the found entry matches the fileName
if idx < len(node.Entries) && node.Entries[idx].Name == fileName {
  return node.Entries[idx], true
}
`

or do you mean `Search` function only returns a boolean?
___
*[`transfer/dir/fs.go` line 115 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5XY2CJCR5hJB74KunX:-O5lo61OAEI1Rf9zKwfM:b4lbuax) ([raw file](https://github.com/0glabs/0g-storage-client/blob/d40e362460291b772bd7d4c51299b36bc3f7939b/transfer/dir/fs.go#L115)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Retrieve the `dir` name from path?
</blockquote></details>

use root dir instead now.


<!-- Sent from Reviewable.io -->

2024-09-02 10:04 UTC, boqiu requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: all files reviewed, 10 unresolved discussions (waiting on @wanliqun)

___
*[`transfer/dir/codec.go` line 39 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m3n2g8sEJOo-fB4cK:-O5m3n2g8sEJOo-fB4cL:bjsyfq6) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L39)):*
> ```Go
> 	// Calculate the total length needed for the byte slice:
> 	// MagicBytes + CodecVersion (2 bytes) + Metadata Length (4 bytes) + JSON Metadata + Optional Raw Data
> 	totalLength := len(CodecMagicBytes) + 2 + 4 + len(mdata)
> ```

If raw data supported, why not calculate the raw data size here?
___
*[`transfer/dir/codec.go` line 63 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m48_K7-ZROA8d3mTm:-O5m48_K7-ZROA8d3mTn:brj1tbc) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L63)):*
> ```Go
> 
> 	// Write raw data to buffer
> 	buf := bytes.NewBuffer(data)
> ```

`offset` not changed after writing JSON data, or should to write raw data from `data[offset:]`.

Is this case covered by unit test?
___
*[`transfer/dir/codec.go` line 92 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m6L5D5wmbsMK5i4Vp:-O5m6L5D5wmbsMK5i4Vq:bksvqiq) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L92)):*
> ```Go
> // It decodes the FsNode from a binary format.
> func (node *FsNode) UnmarshalBinary(data []byte) error {
> 	offset := int64(0)
> ```

`offset` is unnecessary, could change the `data` slice after value retrievd, e.g. data = data[offset:]
___
*[`transfer/dir/codec.go` line 137 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m7mIM0dFPcS5ZrhuN:-O5m7mIM0dFPcS5ZrhuO:b8uvdfu) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L137)):*
> ```Go
> 	// Read and decode raw data
> 	buf := bytes.NewReader(nil)
> 	if offset < datalen {
> ```

is it possible?
___
*[`transfer/dir/codec.go` line 151 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m8B3o46O3nBCv3VEo:-O5m8B3o46O3nBCv3VEp:b-mztb8z) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L151)):*
> ```Go
> 	switch node.Type {
> 	case FileTypeRaw:
> 		data := make([]byte, node.Size)
> ```

Uncessary mem alloc?
___
*[`transfer/dir/codec.go` line 169 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m8MP2E2T6YIID2szn:-O5m8MP2E2T6YIID2szo:b-qx8kuw) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L169)):*
> ```Go
> 	}
> 
> 	return nil
> ```

Check the exact raw data length?
___
*[`transfer/dir/fs.go` line 20 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m8mJh0PSaevDBeHGS:-O5m8mJh0PSaevDBeHGT:butcl3w) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L20)):*
> ```Go
> func init() {
> 	if runtime.GOOS == "windows" {
> 		RootDir = "\\"
> ```

Unnecessary, root dir will not be used as path. Instead, it may be used in http path.
___
*[`transfer/dir/fs.go` line 73 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m9FDZB6EK9xd_SgTo:-O5m9FDZB6EK9xd_SgTp:bbri88r) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L73)):*
> ```Go
> 	root = crypto.Keccak256Hash(entries[0].Hash[:])
> 	for i := 1; i < len(entries); i++ {
> 		root = crypto.Keccak256Hash(entries[i].Hash[:], root[:])
> ```

Suggest to calculate hash in order, e.g. `root = keccak(root, right)`
___
*[`transfer/dir/fs.go` line 91 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m9v938g9N-L2FSb7v:-O5m9v938g9N-L2FSb7w:b9zrane) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L91)):*
> ```Go
> // NewRawFsNode creates a new FsNode representing a raw file.
> func NewRawFsNode(name string, data []byte) (*FsNode, error) {
> 	iterdata, err := core.NewDataInMemory(data)
> ```

What if `data` is empty?
___
*[`transfer/dir/fs.go` line 167 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5mAwUk3myVr5ctvgHk:-O5mAwUk3myVr5ctvgHl:b-xyi1wh) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L167)):*
> ```Go
> 	case info.Mode().IsRegular():
> 		return buildFileNode(path, info)
> 	// TODO: build raw file node based on file size?
> ```

Allow user to specify a threshold to determine if file should be packed as raw data.

On the other hand, it's better add unit test to ensure the root hash of raw data or small file is the same.


<!-- Sent from Reviewable.io -->

2024-09-02 10:30 UTC, boqiu requested changes
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: all files reviewed, 11 unresolved discussions (waiting on @wanliqun)

___
*[`transfer/dir/codec.go` line 144 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5mH1HB67WJep7aYDO3:-O5mH1HB67WJep7aYDO4:b-k49tlm) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L144)):*
> ```Go
> 	}
> 
> 	return nil
> ```

How about to verify root hash at the end of `Unmarshal` to ensure data not changed?


<!-- Sent from Reviewable.io -->

2024-09-03 07:47 UTC, wanliqun reviewed
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: 10 of 16 files reviewed, 11 unresolved discussions (waiting on @boqiu)

___
*[`transfer/dir/codec.go` line 39 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m3n2g8sEJOo-fB4cK:-O5qlbvE-JiFzY-ZTThD:b-5292wb) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L39)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

If raw data supported, why not calculate the raw data size here?
</blockquote></details>

deprecated due to raw file type removed
___
*[`transfer/dir/codec.go` line 63 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m48_K7-ZROA8d3mTm:-O5qlfmi2QAw0l19s49S:b-5292wb) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L63)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`offset` not changed after writing JSON data, or should to write raw data from `data[offset:]`.

Is this case covered by unit test?
</blockquote></details>

deprecated due to raw file type removed
___
*[`transfer/dir/codec.go` line 92 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m6L5D5wmbsMK5i4Vp:-O5qlhGq92qdeVPID25S:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L92)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`offset` is unnecessary, could change the `data` slice after value retrievd, e.g. data = data[offset:]
</blockquote></details>

done
___
*[`transfer/dir/codec.go` line 137 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m7mIM0dFPcS5ZrhuN:-O5qlj1y3kqTt_Da3JwT:b-5292wb) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L137)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

is it possible?
</blockquote></details>

deprecated due to raw file type removed
___
*[`transfer/dir/codec.go` line 144 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5mH1HB67WJep7aYDO3:-O5qljbgCQ8C06XjEIXt:b-3enkgv) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L144)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to verify root hash at the end of `Unmarshal` to ensure data not changed?
</blockquote></details>

Merkle hash is now unset for directory or symbolic file type.
___
*[`transfer/dir/codec.go` line 151 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m8B3o46O3nBCv3VEo:-O5qnA7C-74saBW3emuM:b-5292wb) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L151)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Uncessary mem alloc?
</blockquote></details>

deprecated due to raw file type removed
___
*[`transfer/dir/codec.go` line 169 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m8MP2E2T6YIID2szn:-O5qnAgyC0_SazYnQ8Zw:b-5292wb) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/codec.go#L169)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Check the exact raw data length?
</blockquote></details>

deprecated due to raw file type removed
___
*[`transfer/dir/fs.go` line 20 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m8mJh0PSaevDBeHGS:-O5qnBwk6UcpVjb06o9a:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L20)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Unnecessary, root dir will not be used as path. Instead, it may be used in http path.
</blockquote></details>

done
___
*[`transfer/dir/fs.go` line 73 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m9FDZB6EK9xd_SgTo:-O5qnIAu9VwPchd67UOX:b-3enkgv) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L73)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to calculate hash in order, e.g. `root = keccak(root, right)`
</blockquote></details>

Merkle hash is now unset for directory or symbolic file type.
___
*[`transfer/dir/fs.go` line 91 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5m9v938g9N-L2FSb7v:-O5qnE868pTqksrlZ7U2:b-5292wb) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L91)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

What if `data` is empty?
</blockquote></details>

deprecated due to raw file type removed
___
*[`transfer/dir/fs.go` line 167 at r3](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5mAwUk3myVr5ctvgHk:-O5qnFGB4dl_6VNzEK4-:b-5292wb) ([raw file](https://github.com/0glabs/0g-storage-client/blob/a5cb8bdaa1926a6e4ed0c540cf670d28cbf802ee/transfer/dir/fs.go#L167)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Allow user to specify a threshold to determine if file should be packed as raw data.

On the other hand, it's better add unit test to ensure the root hash of raw data or small file is the same.
</blockquote></details>

deprecated due to raw file type removed


<!-- Sent from Reviewable.io -->

2024-09-03 08:05 UTC, boqiu requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: all files reviewed, 3 unresolved discussions (waiting on @wanliqun)

___
*[`transfer/dir/codec.go` line 88 at r4](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5qtQMe8ayKqORyKVH7:-O5qtQMf5U78XwS9FaUl:b8pp3q4) ([raw file](https://github.com/0glabs/0g-storage-client/blob/4e2a0ffb008e3d352480308d09d6238808529ba3/transfer/dir/codec.go#L88)):*
> ```Go
> 	data = data[2:]
> 
> 	// Read metadata length
> ```

Left data is all for IPLD json data, and length is unnecessary.
___
*[`transfer/dir/fs.go` line 27 at r4](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5quHB91v3QJi3Adan8:-O5quHBA0L4Mo45ieAiC:b-utf53n) ([raw file](https://github.com/0glabs/0g-storage-client/blob/4e2a0ffb008e3d352480308d09d6238808529ba3/transfer/dir/fs.go#L27)):*
> ```Go
> 	Name    string    `json:"name"`              // File or directory name
> 	Type    FileType  `json:"type"`              // File type of the node
> 	Hash    string    `json:"hash,omitempty"`    // Merkle hash (only for regular files)
> ```

`Root` or `MerkleRoot` is more meaningful.



_Code quote:_
```Go
Hash
```
___
*[`transfer/dir/fs.go` line 85 at r4](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5quXtlAorGKdEx9DKK:-O5quXtlAorGKdEx9DKL:b-687g0l) ([raw file](https://github.com/0glabs/0g-storage-client/blob/4e2a0ffb008e3d352480308d09d6238808529ba3/transfer/dir/fs.go#L85)):*
> ```Go
> 	switch node.Type {
> 	case FileTypeFile:
> 		return node.Hash == rhs.Hash && node.Size == rhs.Size
> ```

Compare the root hash is enough.


<!-- Sent from Reviewable.io -->

2024-09-03 08:13 UTC, wanliqun reviewed
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @boqiu)

___
*[`transfer/dir/codec.go` line 88 at r4](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5qtQMe8ayKqORyKVH7:-O5qwR935MBK4U9VstBU:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/4e2a0ffb008e3d352480308d09d6238808529ba3/transfer/dir/codec.go#L88)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Left data is all for IPLD json data, and length is unnecessary.
</blockquote></details>

done
___
*[`transfer/dir/fs.go` line 27 at r4](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5quHB91v3QJi3Adan8:-O5qwSyaDIJ5VBXZSqt1:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/4e2a0ffb008e3d352480308d09d6238808529ba3/transfer/dir/fs.go#L27)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`Root` or `MerkleRoot` is more meaningful.
</blockquote></details>

done
___
*[`transfer/dir/fs.go` line 85 at r4](https://reviewable.io/reviews/0glabs/0g-storage-client/43#-O5quXtlAorGKdEx9DKK:-O5qwU-I4CyYFrrW1XOq:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/4e2a0ffb008e3d352480308d09d6238808529ba3/transfer/dir/fs.go#L85)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Compare the root hash is enough.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-09-03 08:48 UTC, boqiu approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/43)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wanliqun)



<!-- Sent from Reviewable.io -->

2024-09-03 08:54 UTC, merged