feat: add segment upload RESTful API for indexer gateway
0glabs/0g-storage-client pull request #64
Opened 2024-10-16 10:04 UTC by wanliqun

- Implement `SegmentWithProofUploader` for parallel batch segment uploads
- Refactor common segment calculation logic for reuse and clarity

2024-10-16 11:17 UTC, MiniFrenchBread requested changes

2024-10-16 11:17 UTC, MiniFrenchBread commented on cmd/indexer.go
> +	indexerCmd.Flags().UintVar(&indexerArgs.ExpectedReplica, "expected-replica", 2, "Expected number of replications to upload")
2 for default value is too strict, 1 is fine

2024-10-16 11:17 UTC, MiniFrenchBread commented on indexer/gateway/download.go
> +		if root != "" {
change txSeq type to a pointer and try to get file info by txSeq first

2024-10-16 11:17 UTC, MiniFrenchBread commented on indexer/gateway/upload.go
> +	Root  string          `form:"root" json:"root" binding:"required"`   // File merkle root
Can we replace the root with txSeq, or add a new field for txSeq here?

In sharding scenario, there may be files with same root but different txSeq, their starting positions on the flow may also be different, which makes the segments that the same node needs to store for these identical files different for each one.

2024-10-17 07:24 UTC, wanliqun reviewed
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/64)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @boqiu and @MiniFrenchBread)

___
*[`cmd/indexer.go` line 48 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/64#gh-1802884946:-O9OMCAQDatylP8v1XQh:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/eb68b4127d7f2fd689b3607c914a7d8373aa0d8c/cmd/indexer.go#L48)):*
<details><summary><i>Previously, MiniFrenchBread wrote…</i></summary><blockquote>

2 for default value is too strict, 1 is fine
</blockquote></details>

Done.
___
*[`indexer/gateway/download.go` line 150 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/64#gh-1802892691:-O9OMFApEMRswgNHzlJR:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/eb68b4127d7f2fd689b3607c914a7d8373aa0d8c/indexer/gateway/download.go#L150)):*
<details><summary><i>Previously, MiniFrenchBread wrote…</i></summary><blockquote>

change txSeq type to a pointer and try to get file info by txSeq first
</blockquote></details>

Done.
___
*[`indexer/gateway/upload.go` line 21 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/64#gh-1802902082:-O9OMHwY0DV5w9BZH28-:b-896fix) ([raw file](https://github.com/0glabs/0g-storage-client/blob/eb68b4127d7f2fd689b3607c914a7d8373aa0d8c/indexer/gateway/upload.go#L21)):*
<details><summary><i>Previously, MiniFrenchBread wrote…</i></summary><blockquote>

Can we replace the root with txSeq, or add a new field for txSeq here?

In sharding scenario, there may be files with same root but different txSeq, their starting positions on the flow may also be different, which makes the segments that the same node needs to store for these identical files different for each one.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-17 09:58 UTC, MiniFrenchBread approved these changes

2024-10-21 07:45 UTC, merged